// _lib/timeline.ts

export type TimelineEventType =
  | "ospite"
  | "presentazione"
  | "esibizione"
  | "spot"
  | "collegamento"
  | "fine"
  | "momento_speciale"
  | "premio"
  | "stop_televoto"
  | "classifica_finale";

type EventBase = {
  time: string;
  label: string;
  duration?: string;
  presenter?: string;
  aiContext?: string;
};

export type TimelineEvent = EventBase & (
  | { type: "ospite"; description?: string; guest: string; songs?: string[] }
  | { type: "presentazione"; description?: string; guest?: string; songs?: string[] }
  | { type: "esibizione"; songId?: number; coverTitle: string; description?: string; televotoCode?: string }
  | { type: "spot" }
  | { type: "collegamento"; description?: string; guest?: string; songs?: string[] }
  | { type: "fine"; description: string }
);

export const SERATA_TIMELINE: TimelineEvent[] = [
  {
    time: "20:40",
    type: "presentazione",
    label: "Apertura serata",
    presenter: "Carlo Conti, Laura Pausini, Giorgia Cardinaletti",
    duration: "2'",
    aiContext: "È il 76° Festival di Sanremo e Carlo Conti è tornato al comando come se non avesse mai smesso. Al suo fianco Laura Pausini (una delle cantanti italiane più famose al mondo, lei lo sa benissimo) e Giorgia Cardinaletti del TG1. Si parte.",
  },
  {
    time: "20:42",
    type: "presentazione",
    label: "Regolamento e codici televoto",
    description: "30 artisti in gara. Voti: 33% Sala Stampa/TV/Web, 33% Radio, 34% Televoto. Televoto: 894.001 da fisso, 475.475.1 SMS.",
    presenter: "Carlo Conti",
    duration: "2'",
    aiContext: "Conti legge 30 codici televoto uno per uno. È la serata delle cover, ma prima tocca sorbirsi l'equivalente musicale dei termini e condizioni di un'app.",
  },
  {
    time: "20:44",
    type: "presentazione",
    label: "Ingresso co-conduttrice",
    presenter: "Carlo Conti",
    guest: "Laura Pausini",
    duration: "1'",
    aiContext: "Laura Pausini entra sul palco. Ha venduto 70 milioni di dischi. Probabilmente lo dirà.",
  },
  {
    time: "20:45",
    type: "esibizione",
    songId: 29,
    label: "Francesco Renga",
    coverTitle: "Il meglio di me",
    presenter: "Carlo Conti e Laura Pausini",
    televotoCode: "01",
    duration: "2'46\"",
    aiContext: "Francesco Renga apre la serata delle cover con 'Il meglio di me' di Antonello Venditti. Renga ha una voce potente e un'intensità sul palco che fa sembrare ogni canzone un addio drammatico. Codice televoto 01, primo della lista, probabile vantaggio psicologico.",
  },
  {
    time: "20:50",
    type: "esibizione",
    songId: 26,
    label: "Chiello",
    coverTitle: "Ti penso sempre",
    presenter: "Carlo Conti e Laura Pausini",
    televotoCode: "02",
    duration: "2'35\"",
    aiContext: "Chiello è un rapper/cantante della nuova generazione. 'Ti penso sempre' è un brano di Lucio Battisti. Abbinamento generazionale coraggioso — o folle, dipende dai punti di vista.",
  },
  {
    time: "20:55",
    type: "presentazione",
    label: "Ingresso comico",
    description: "Decalogo del direttore artistico.",
    presenter: "Carlo Conti",
    guest: "Nino Frassica",
    duration: "3'",
    aiContext: "Nino Frassica è il jolly comico della serata. Conti lo usa come scudo anti-noia tra un'esibizione e l'altra. Il decalogo del direttore artistico è probabilmente una serie di regole inventate che non ha senso ma fa ridere.",
  },
  {
    time: "20:58",
    type: "esibizione",
    songId: 12,
    label: "Raf",
    coverTitle: "Ora e per sempre",
    presenter: "Carlo Conti e Nino Frassica",
    televotoCode: "03",
    duration: "3'13\"",
    aiContext: "Raf canta 'Ora e per sempre' di Riccardo Cocciante. Raf è uno dei big degli anni '80 e '90, voce inconfondibile. Il pubblico over 40 sta già piangendo preventivamente.",
  },
  {
    time: "21:04",
    type: "spot",
    label: "Pubblicità",
    duration: "5'",
    aiContext: "Pausa pubblicitaria. Cinque minuti per andare in bagno, litigare con i familiari sul televoto o aprire Twitter a leggere i commenti al veleno.",
  },
  {
    time: "21:09",
    type: "esibizione",
    songId: 25,
    label: "Bambole di Pezza",
    coverTitle: "Resta con me",
    description: "2 chitarre, 1 basso, 1 batteria.",
    presenter: "Carlo Conti e Laura Pausini",
    televotoCode: "04",
    duration: "3'06\"",
    aiContext: "Bambole di Pezza sono una band indie-rock. Coprono 'Resta con me' di Pino Daniele. Setup minimale: 2 chitarre, basso, batteria. Niente fronzoli, solo musica. Sul palco dell'Ariston questo è già rivoluzionario.",
  },
  {
    time: "21:14",
    type: "presentazione",
    label: "Ingresso co-conduttrice",
    presenter: "Carlo Conti e Laura Pausini",
    guest: "Giorgia Cardinaletti",
    duration: "2'",
    aiContext: "Giorgia Cardinaletti entra in scena. Giornalista del TG1, portamento istituzionale, probabilmente l'unica persona sul palco che non ha un album da promuovere.",
  },
  {
    time: "21:16",
    type: "esibizione",
    songId: 28,
    label: "Leo Gassmann",
    coverTitle: "Naturale",
    presenter: "Carlo Conti, Laura Pausini e Giorgia Cardinaletti",
    televotoCode: "05",
    duration: "3'00\"",
    aiContext: "Leo Gassmann, figlio di Alessandro Gassmann, nipote di Vittorio Gassmann. Canta 'Naturale' di Zucchero. Il cognome pesa, ma la voce regge.",
  },
  {
    time: "21:22",
    type: "esibizione",
    songId: 20,
    label: "Malika Ayane",
    coverTitle: "Animali notturni",
    description: "Con Luca Faraone chitarrista e bottiglie di vetro.",
    presenter: "Carlo Conti e Nino Frassica",
    televotoCode: "06",
    duration: "2'56\"",
    aiContext: "Malika Ayane è una delle artiste più raffinate del panorama italiano. Canta 'Animali notturni' di Subsonica. Da notare: bottiglie di vetro usate come strumenti. Sì, bottiglie. Sanremo è Sanremo.",
  },
  {
    time: "21:28",
    type: "esibizione",
    songId: 8,
    label: "Tommaso Paradiso",
    coverTitle: "I romantici",
    presenter: "Carlo Conti e Laura Pausini",
    televotoCode: "07",
    duration: "3'46\"",
    aiContext: "Ex frontman dei TheGiornalisti, Tommaso Paradiso è il re indiscusso delle canzoni che ascolti a 23 anni credendo di capire il dolore. Canta 'I romantici' di Scialpi. Tre minuti e 46 secondi di nostalgia millennial garantita.",
  },
  {
    time: "21:34",
    type: "esibizione",
    songId: 13,
    label: "J-AX",
    coverTitle: "Italia starter pack",
    description: "1 violinista, 1 banjo, 5 cheerleader acrobatiche, 4 squaredancer.",
    presenter: "Carlo Conti e Giorgia Cardinaletti",
    televotoCode: "08",
    duration: "2'52\"",
    aiContext: "J-AX porta sul palco 'Italia starter pack' con violinista, banjo, cheerleader acrobatiche e squaredancer. In pratica ha costruito uno show nel mezzo della serata delle cover. Il brano originale è di Elio e le Storie Tese. Caos controllato.",
  },
  {
    time: "21:39",
    type: "spot",
    label: "Pubblicità",
    duration: "5'",
    aiContext: "Altra pausa pubblicitaria. I social stanno già esplodendo per J-AX.",
  },
  {
    time: "21:44",
    type: "esibizione",
    songId: 30,
    label: "LDA & AKA 7EVEN",
    coverTitle: "Poesie clandestine",
    description: "20-30 ballerini tra il pubblico e in galleria.",
    presenter: "Carlo Conti e Nino Frassica",
    televotoCode: "09",
    duration: "2'58\"",
    aiContext: "LDA (figlio di Gigi D'Alessio) e AKA 7EVEN si sono conosciuti ad Amici. Portano 'Poesie clandestine' di Pierangelo Bertoli con 20-30 ballerini distribuiti tra platea e galleria. Effetto spettacolare praticamente garantito.",
  },
  {
    time: "21:50",
    type: "presentazione",
    label: "Momento TIM",
    description: "Il pubblico canta con l'orchestra. I braccialetti si colorano di blu e rosso.",
    presenter: "Carlo Conti",
    songs: ["Come saprei"],
    duration: "3'",
    aiContext: "Momento sponsorizzato TIM in cui tutto il teatro canta 'Come saprei' di Giorgia (1995) accompagnato dall'orchestra. I braccialetti led regalati all'ingresso diventano blu e rosso. Emozionante o inquietante, dipende da quanto sei cinico.",
  },
  {
    time: "21:53",
    type: "esibizione",
    songId: 18,
    label: "Serena Brancale",
    coverTitle: "Qui con me",
    presenter: "Carlo Conti e Laura Pausini",
    televotoCode: "10",
    duration: "3'11\"",
    aiContext: "Serena Brancale ha spopolato con 'Anema e core' portata a Sanremo 2024. Quest'anno cover e codice 10. Voce jazz-soul, presenza scenica notevole. Da tenere d'occhio.",
  },
  {
    time: "21:59",
    type: "presentazione",
    label: "Gag: il vero Sandokan",
    description: "Frassica presenta Gigi Rock come 'il vero Sandokan', con foto di Can Yaman.",
    presenter: "Carlo Conti e Nino Frassica",
    guest: "Gigi Rock",
    duration: "4'",
    aiContext: "Frassica interrompe la serata per presentare Gigi Rock come 'il vero Sandokan', mostrando una foto di Can Yaman per confronto. Gag nonsense pura. Can Yaman non sa cosa sta succedendo sul palco dell'Ariston.",
  },
  {
    time: "22:03",
    type: "esibizione",
    songId: 10,
    label: "Patty Pravo",
    coverTitle: "Opera",
    presenter: "Carlo Conti e Nino Frassica",
    televotoCode: "11",
    duration: "3'38\"",
    aiContext: "Patty Pravo è una leggenda vivente della musica italiana, in carriera dagli anni '60. Canta 'Opera' di Edoardo Bennato. Ogni sua apparizione a Sanremo è un evento in sé, indipendentemente dalla canzone.",
  },
  {
    time: "22:09",
    type: "esibizione",
    songId: 22,
    label: "Sal Da Vinci",
    coverTitle: "Per sempre sì",
    presenter: "Carlo Conti e Giorgia Cardinaletti",
    televotoCode: "12",
    duration: "2'52\"",
    aiContext: "Sal Da Vinci è un pilastro della canzone napoletana contemporanea. 'Per sempre sì' è un brano romantico nel senso più classico del termine. Il pubblico campano è già in piedi.",
  },
  {
    time: "22:14",
    type: "ospite",
    label: "Ospite speciale",
    description: "Arriva a cavallo dall'esterno dell'Ariston, percorre il foyer sulle note del Gladiatore, poi sale sul palco. Premio Città di Sanremo consegnato da Alessandro Sindoni.",
    presenter: "Carlo Conti e Laura Pausini",
    guest: "Andrea Bocelli",
    songs: ["Il mare calmo della sera", "Con te partirò"],
    duration: "20'",
    aiContext: "Andrea Bocelli arriva letteralmente a cavallo davanti all'Ariston. Non in macchina. A cavallo. Entra nel foyer sulle note del Gladiatore come se stesse conquistando Roma. È il tenore più famoso al mondo e lo sa. Canta due brani, riceve il Premio Città di Sanremo. Venti minuti di puro spettacolo.",
  },
  {
    time: "22:34",
    type: "spot",
    label: "Pubblicità",
    duration: "5'",
    aiContext: "Pausa dopo Bocelli. Il pubblico in sala sta ancora cercando di riprendersi dall'ingresso a cavallo.",
  },
  {
    time: "22:39",
    type: "esibizione",
    songId: 9,
    label: "Elettra Lamborghini",
    coverTitle: "Voilà",
    description: "6 ballerini con ventaglio.",
    presenter: "Carlo Conti e Laura Pausini",
    televotoCode: "13",
    duration: "3'10\"",
    aiContext: "Elettra Lamborghini, ereditiera e performer, porta 'Voilà' di Barbara con 6 ballerini e ventagli. Non è esattamente il profilo dell'interprete drammatica, ma l'intrattenimento è assicurato. La sua partecipazione a Sanremo 2020 ('Musica (e il resto scompare)') è già leggenda.",
  },
  {
    time: "22:44",
    type: "presentazione",
    label: "Conti al Suzuki Stage",
    description: "Conti esce verso Piazza Colombo.",
    presenter: "Carlo Conti",
    duration: "2'",
    aiContext: "Carlo Conti abbandona l'Ariston e cammina fino a Piazza Colombo per il collegamento con i Pooh. Sanremo è piccola, ma questo è comunque un evento.",
  },
  {
    time: "22:46",
    type: "collegamento",
    label: "Suzuki Stage",
    description: "60 anni di carriera. Conti consegna la targa 'Premio città di Sanremo – Amici per sempre'.",
    guest: "Pooh",
    songs: ["Uomini soli"],
    duration: "7'",
    aiContext: "I Pooh festeggiano 60 anni di carriera. Sessanta. Hanno iniziato nel 1966. 'Uomini soli' ha vinto Sanremo nel 1990. Chiunque abbia più di 35 anni sta avendo un momento emotivo non richiesto.",
  },
  {
    time: "22:53",
    type: "spot",
    label: "Pubblicità",
    duration: "5'",
    aiContext: "Pubblicità. Conti sta probabilmente correndo a riprendersi un posto sul palco.",
  },
  {
    time: "22:58",
    type: "presentazione",
    label: "Cambio d'abito",
    presenter: "Carlo Conti e Laura Pausini",
    guest: "Giorgia Cardinaletti",
    duration: "1'",
    aiContext: "Giorgia Cardinaletti rientra con un nuovo abito. Il cambio d'abito a Sanremo è un'istituzione quasi quanto il Festival stesso.",
  },
  {
    time: "22:59",
    type: "esibizione",
    songId: 17,
    label: "Ermal Meta",
    coverTitle: "Stella stellina",
    presenter: "Carlo Conti, Laura Pausini e Giorgia Cardinaletti",
    televotoCode: "14",
    duration: "3'19\"",
    aiContext: "Ermal Meta è uno dei cantautori più apprezzati della sua generazione. 'Stella stellina' è una filastrocca tradizionale reinterpretata. Contrasto tra l'innocenza del testo originale e la profondità che Meta ci mette dentro.",
  },
  {
    time: "23:05",
    type: "esibizione",
    songId: 1,
    label: "Ditonellapiaga",
    coverTitle: "Che fastidio!",
    description: "Con sei ballerine e tutta l'orchestra con occhiali.",
    presenter: "Carlo Conti e Laura Pausini",
    televotoCode: "15",
    duration: "3'14\"",
    aiContext: "Ditonellapiaga è l'artista indie-pop più irriverente in gara. 'Che fastidio!' è di Elio e le Storie Tese. Tutta l'orchestra indossa occhiali. Non è un errore. È una scelta artistica deliberata e magnifica.",
  },
  {
    time: "23:10",
    type: "presentazione",
    label: "Conti in platea",
    presenter: "Carlo Conti",
    duration: "2'",
    aiContext: "Conti scende in platea tra il pubblico. Momento interazione umana, telecamere che inseguono facce famose in prima fila.",
  },
  {
    time: "23:12",
    type: "presentazione",
    label: "Riepilogo codici televoto",
    description: "Televoto: 894.001 da fisso, 475.475.1 SMS.",
    presenter: "Carlo Conti",
    duration: "1'",
    aiContext: "Conti rilegge tutti e 30 i codici televoto. Di nuovo. Per chi fosse entrato in casa ora o fosse stato in bagno dalle 20:42.",
  },
  {
    time: "23:13",
    type: "esibizione",
    songId: 19,
    label: "NAYT",
    coverTitle: "Prima che",
    presenter: "Carlo Conti e Giorgia Cardinaletti",
    televotoCode: "16",
    duration: "3'01\"",
    aiContext: "NAYT è uno dei rapper italiani più interessanti della scena attuale, noto per testi introspettivi e sonorità cupe. Cover di 'Prima che' di Franco Battiato. Abbinamento insolito che potrebbe funzionare benissimo o essere un esperimento sociologico.",
  },
  {
    time: "23:18",
    type: "presentazione",
    label: "TLP ENI",
    duration: "1'",
    aiContext: "Momento sponsorizzato ENI. Tutti fingono di essere interessati.",
  },
  {
    time: "23:19",
    type: "presentazione",
    label: "Gag: Novella Bella Sanremo",
    description: "Frassica legge le sue notizie inventate.",
    presenter: "Carlo Conti e Nino Frassica",
    duration: "3'",
    aiContext: "Frassica torna con le sue notizie inventate dal giornale immaginario 'Novella Bella Sanremo'. Il format è semplice: titoli di notizie assurde lette con assoluta serietà. Funziona sempre.",
  },
  {
    time: "23:22",
    type: "esibizione",
    songId: 6,
    label: "Arisa",
    coverTitle: "Magica favola",
    presenter: "Carlo Conti e Nino Frassica",
    televotoCode: "17",
    duration: "3'28\"",
    aiContext: "Arisa è una delle voci più potenti e particolari della musica italiana. Ha già vinto Sanremo due volte. 'Magica favola' è di Anna Oxa. Scontro tra due personalità vocali enormi: chi vince?",
  },
  {
    time: "23:28",
    type: "esibizione",
    songId: 3,
    label: "SAYF",
    coverTitle: "Tu mi piaci tanto",
    description: "Asta con base circolare.",
    presenter: "Carlo Conti e Laura Pausini",
    televotoCode: "18",
    duration: "3'28\"",
    aiContext: "SAYF è un giovane cantautore con influenze R&B. Usa un'asta con base circolare come elemento scenico. 'Tu mi piaci tanto' è un brano del repertorio pop italiano. Semplice e diretto.",
  },
  {
    time: "23:33",
    type: "presentazione",
    label: "Lancio collegamento Costa Crociere",
    presenter: "Carlo Conti",
    duration: "1'",
    aiContext: "Conti annuncia il prossimo collegamento con la nave Costa Toscana. Sanremo incontra il turismo di lusso sul mare.",
  },
  {
    time: "23:34",
    type: "spot",
    label: "Pubblicità — Fine prima parte",
    duration: "5'",
    aiContext: "Fine della prima parte. Siamo quasi a mezzanotte e mancano ancora 12 artisti. Benvenuti a Sanremo.",
  },
  {
    time: "23:39",
    type: "collegamento",
    label: "Costa Crociere",
    description: "Dalla nave Costa Toscana.",
    guest: "Max Pezzali",
    songs: ["Come mai", "Nessun rimpianto"],
    duration: "6'",
    aiContext: "Max Pezzali si esibisce dalla nave Costa Toscana in mezzo al mare. Fondatore degli 883, ha scritto l'inno generazionale di ogni millennial italiano. 'Come mai' e 'Nessun rimpianto' sono praticamente patrimonio culturale nazionale.",
  },
  {
    time: "23:45",
    type: "presentazione",
    label: "Ingresso ospiti speciali",
    description: "Le tre entrano sulle note di Charlie's Angels.",
    presenter: "Carlo Conti",
    guest: "Manola Moslehi, Carolina Rey, Ema Stokholma",
    duration: "2'",
    aiContext: "Tre conduttrici radiofoniche e televisive entrano sulle note di Charlie's Angels. Il riferimento agli anni '70 è voluto. Presenteranno i prossimi artisti in gara.",
  },
  {
    time: "23:47",
    type: "esibizione",
    songId: 15,
    label: "Levante",
    coverTitle: "Sei tu",
    presenter: "Carlo Conti, Manola Moslehi, Carolina Rey ed Ema Stokholma",
    televotoCode: "19",
    duration: "3'30\"",
    aiContext: "Levante è una delle cantautrici più letterarie e visive della scena italiana. Canta 'Sei tu' di Pino Donaggio. Aspettati intensità scenica e almeno un momento in cui tutto il teatro trattiene il respiro.",
  },
  {
    time: "23:53",
    type: "esibizione",
    songId: 16,
    label: "Fedez & Masini",
    coverTitle: "Male necessario",
    presenter: "Carlo Conti e Nino Frassica",
    televotoCode: "20",
    duration: "3'04\"",
    aiContext: "Fedez e Marco Masini: il rapper più seguito sui social d'Italia incontra il cantautore che ha scritto 'Vaffanculo'. 'Male necessario' è degli Afterhours. È il crossover che nessuno aveva chiesto e che tutti guarderanno comunque.",
  },
  {
    time: "23:59",
    type: "presentazione",
    label: "GM",
    duration: "1'",
    aiContext: "Breve spazio promozionale. È quasi mezzanotte, la gente normale sta dormendo.",
  },
  {
    time: "00:00",
    type: "presentazione",
    label: "Cambio d'abito",
    presenter: "Carlo Conti",
    guest: "Laura Pausini",
    duration: "1'",
    aiContext: "È mezzanotte e Laura Pausini cambia abito. Sanremo non dorme mai.",
  },
  {
    time: "00:01",
    type: "esibizione",
    songId: 11,
    label: "Samurai Jay",
    coverTitle: "Ossessione",
    description: "La mamma di Samurai Jay + 6 ballerini.",
    presenter: "Carlo Conti e Laura Pausini",
    televotoCode: "21",
    duration: "3'06\"",
    aiContext: "Samurai Jay è uno dei nomi più freschi in gara. Porta sul palco la propria madre, letteralmente. Sei ballerini completano lo show. 'Ossessione' di Francesco Baccini diventa un momento di famiglia e spettacolo insieme.",
  },
  {
    time: "00:07",
    type: "esibizione",
    songId: 2,
    label: "Michele Bravi",
    coverTitle: "Prima o poi",
    presenter: "Carlo Conti e Giorgia Cardinaletti",
    televotoCode: "22",
    duration: "2'58\"",
    aiContext: "Michele Bravi ha una delle storie più toccanti tra gli artisti in gara, segnata da un periodo di grande fragilità pubblica da cui è uscito con grazia. Canta con una delicatezza che disarma. 'Prima o poi' è di Mango.",
  },
  {
    time: "00:13",
    type: "presentazione",
    label: "Spot Liguria",
    duration: "1'",
    aiContext: "La Regione Liguria si ricorda che il Festival è a casa sua.",
  },
  {
    time: "00:14",
    type: "presentazione",
    label: "Gag: Novella Bella Sanremo 2",
    description: "Secondo intervento comico di Frassica con le sue notizie inventate.",
    presenter: "Carlo Conti e Nino Frassica",
    duration: "5'",
    aiContext: "Frassica torna con il secondo round di notizie inventate. Cinque minuti alle 00:14 di notte. Il festival è un maratona e Frassica è l'energy drink.",
  },
  {
    time: "00:19",
    type: "esibizione",
    songId: 14,
    label: "Fulminacci",
    coverTitle: "Stupida fortuna",
    presenter: "Carlo Conti e Nino Frassica",
    televotoCode: "23",
    duration: "2'50\"",
    aiContext: "Fulminacci è uno dei cantautori più originali della sua generazione, noto per testi intelligenti e ironici. 'Stupida fortuna' è di Luigi Tenco. Un classico della malinconia italiana affidato a uno dei suoi eredi più credibili.",
  },
  {
    time: "00:24",
    type: "presentazione",
    label: "Ingresso ospite",
    presenter: "Carlo Conti e Laura Pausini",
    guest: "Nicola Savino",
    duration: "2'",
    aiContext: "Nicola Savino, conduttore di Lol e volto storico di Radio DeeJay, entra per presentare i prossimi artisti. Amico di lunga data di Conti, probabilmente faranno battute reciproche.",
  },
  {
    time: "00:26",
    type: "esibizione",
    songId: 7,
    label: "Luchè",
    coverTitle: "Labirinto",
    presenter: "Carlo Conti, Laura Pausini e Nicola Savino",
    televotoCode: "24",
    duration: "3'45\"",
    aiContext: "Luchè è uno dei rapper più rispettati d'Italia, con radici nella scena napoletana. 'Labirinto' è di Lucio Battisti. Tre minuti e 45 secondi per vedere come un rapper del Sud reinterpreta il mito del cantautorato italiano.",
  },
  {
    time: "00:32",
    type: "spot",
    label: "Pubblicità",
    duration: "5'",
    aiContext: "Pausa pubblicitaria. Manca meno di un'ora alla fine. Ce la fai.",
  },
  {
    time: "00:37",
    type: "presentazione",
    label: "TG1 Sera",
    duration: "1'",
    aiContext: "Il TG1 ricorda che esiste anche il resto del mondo. Brevemente.",
  },
  {
    time: "00:38",
    type: "presentazione",
    label: "Minuto di silenzio — femminicidio",
    description: "Sul ledwall scorrono nomi di donne. Gino Cecchettin sale sul palco, poi interviene Laura Pausini.",
    presenter: "Carlo Conti e Laura Pausini",
    guest: "Gino Cecchettin",
    duration: "4'",
    aiContext: "Momento di grande peso emotivo. Gino Cecchettin, padre di Giulia Cecchettin, sale sul palco. Sul ledwall scorrono i nomi delle vittime di femminicidio. Laura Pausini interviene. Non è intrattenimento, è memoria.",
  },
  {
    time: "00:42",
    type: "esibizione",
    songId: 24,
    label: "Tredici Pietro",
    coverTitle: "Uomo che cade",
    presenter: "Carlo Conti e Laura Pausini",
    televotoCode: "25",
    duration: "3'36\"",
    aiContext: "Tredici Pietro è un rapper/cantautore con un'estetica molto personale. 'Uomo che cade' è di Lucio Dalla. L'abbinamento è sorprendente sulla carta, ma Dalla è sempre stato trasversale.",
  },
  {
    time: "00:48",
    type: "esibizione",
    songId: 4,
    label: "Mara Sattei",
    coverTitle: "Le cose che non sai di me",
    presenter: "Carlo Conti e Giorgia Cardinaletti",
    televotoCode: "26",
    duration: "3'23\"",
    aiContext: "Mara Sattei è la sorella di tha Supreme, uno dei produttori più influenti della musica italiana. Ha una voce eterea e uno stile minimalista. 'Le cose che non sai di me' è di Mia Martini, uno dei brani più fragili e profondi della musica italiana.",
  },
  {
    time: "00:54",
    type: "spot",
    label: "Pubblicità",
    duration: "5'",
    aiContext: "Ultima pausa pubblicitaria della serata. Siamo quasi alla fine.",
  },
  {
    time: "00:59",
    type: "esibizione",
    songId: 5,
    label: "Dargen D'Amico",
    coverTitle: "AI AI",
    presenter: "Carlo Conti e Laura Pausini",
    televotoCode: "27",
    duration: "3'19\"",
    aiContext: "Dargen D'Amico è il jolly creativo del festival, sempre imprevedibile. Il titolo 'AI AI' fa già intuire che il brano avrà a che fare con l'intelligenza artificiale. Dargen è il tipo di artista che trasforma un concept in spettacolo.",
  },
  {
    time: "01:05",
    type: "esibizione",
    songId: 23,
    label: "Enrico Nigiotti",
    coverTitle: "Ogni volta che non so volare",
    presenter: "Carlo Conti e Nino Frassica",
    televotoCode: "28",
    duration: "2'58\"",
    aiContext: "Enrico Nigiotti è un veterano di Amici con una voce vissuta. 'Ogni volta che non so volare' è un brano intenso. Alle 01:05 di notte, chi è ancora sveglio è pronto per l'emotività senza filtri.",
  },
  {
    time: "01:10",
    type: "esibizione",
    songId: 27,
    label: "Maria Antonietta & Colombre",
    coverTitle: "La felicità e basta",
    description: "Lei con omnichord, lui con chitarra.",
    presenter: "Carlo Conti e Giorgia Cardinaletti",
    televotoCode: "29",
    duration: "3'25\"",
    aiContext: "Duo indie-folk con omnichord e chitarra. 'La felicità e basta' è di Lucio Battisti. Setup essenziale e intimo in un palco da 2000 persone. Coraggioso. L'omnichord è uno strumento elettronico anni '80 che suona come un sogno.",
  },
  {
    time: "01:16",
    type: "esibizione",
    songId: 21,
    label: "Eddie Brock",
    coverTitle: "Avvoltoi",
    presenter: "Carlo Conti e Laura Pausini",
    televotoCode: "30",
    duration: "2'42\"",
    aiContext: "Eddie Brock chiude la carrellata di cover come ultimo dei 30. Nome ispirato al personaggio Marvel. 'Avvoltoi' è di Vasco Rossi. Chiudere con Vasco è sempre una scelta sicura.",
  },
  {
    time: "01:22",
    type: "presentazione",
    label: "Stop al televoto",
    description: "Televoto: 894.001 da fisso, 475.475.1 SMS.",
    presenter: "Carlo Conti",
    duration: "1'",
    aiContext: "Conti chiude ufficialmente il televoto. Da questo momento non si può più votare. Le sorti del festival sono nelle mani del pubblico, della sala stampa e della giuria radio.",
  },
  {
    time: "01:23",
    type: "presentazione",
    label: "Gag: il provino",
    description: "Gag con tavolino e 2 sedie.",
    presenter: "Carlo Conti e Nino Frassica",
    guest: "Padda (Francesco Scali), Pietro Pulcini",
    duration: "5'",
    aiContext: "Frassica torna per l'ultima gag della notte con Padda e Pietro Pulcini. Un tavolino, due sedie e probabilmente assurdità pura. A quest'ora è esattamente quello che serve.",
  },
  {
    time: "01:28",
    type: "collegamento",
    label: "Rai Radio 2 — Blue Room",
    description: "Conti ricorda che il vincitore andrà all'Eurovision a Vienna, finale il 16 maggio.",
    guest: "Ema Stokholma, Gino Castaldo",
    duration: "2'",
    aiContext: "Collegamento con la Blue Room di Rai Radio 2, il backstage ufficiale del festival. Ema Stokholma e il critico musicale Gino Castaldo commentano la serata. Conti ricorda che il vincitore andrà all'Eurovision Song Contest a Vienna.",
  },
  {
    time: "01:30",
    type: "presentazione",
    label: "Classifica dal 30° al 6° posto",
    description: "I Big sono visibili in backstage.",
    presenter: "Carlo Conti",
    duration: "4'",
    aiContext: "Conti legge la classifica dal 30° al 6° posto. I 30 artisti aspettano in backstage il loro destino. Quattro minuti di tensione collettiva.",
  },
  {
    time: "01:34",
    type: "presentazione",
    label: "Annuncio dei 5 finalisti e televoto finale",
    description: "I 5 finalisti rivelati in ordine notarile. Televoto finale: 1 solo voto, votano anche sala stampa e giuria radio.",
    presenter: "Carlo Conti",
    duration: "5'",
    aiContext: "I 5 finalisti vengono rivelati. Da qui si vota di nuovo, ma con un solo voto a testa. Anche sala stampa e giuria radio riprendono a votare. Il televoto finale è il momento più caotico e importante della serata.",
  },
  {
    time: "01:39",
    type: "spot",
    label: "Pubblicità",
    duration: "5'",
    aiContext: "Pubblicità mentre si vota. L'Italia intera sta litigando su chi votare.",
  },
  {
    time: "01:44",
    type: "ospite",
    label: "Esibizione",
    description: "Band di 4 elementi, 4 coristi, 4 aste luminose.",
    presenter: "Carlo Conti",
    guest: "Laura Pausini",
    songs: ["In assenza di te", "Incancellabile", "Invece no"],
    duration: "6'",
    aiContext: "Laura Pausini smette di fare la conduttrice e diventa la Laura Pausini. Tre brani, band al completo, coristi, aste luminose. 70 milioni di dischi venduti nel mondo. Questo è il momento in cui si ricorda perché è sul palco.",
  },
  {
    time: "01:50",
    type: "presentazione",
    label: "Stop al televoto finale",
    description: "Conti raggiunge i 5 finalisti in backstage per battute a caldo.",
    presenter: "Carlo Conti",
    duration: "2'",
    aiContext: "Il televoto finale chiude. Conti va in backstage a intervistare i 5 finalisti. È il momento in cui tutti fingono di essere rilassati e non lo sono per niente.",
  },
  {
    time: "01:51",
    type: "presentazione",
    label: "Premi speciali",
    description: "Premio della critica Mia Martini, Premio Sala Stampa Lucio Dalla, Premio Sergio Bardotti miglior testo, Premio Giancarlo Bigazzi miglior composizione musicale.",
    presenter: "Carlo Conti",
    duration: "5'",
    aiContext: "Vengono assegnati i premi collaterali del Festival: Mia Martini per la critica, Lucio Dalla dalla sala stampa, Bardotti per il miglior testo, Bigazzi per la miglior composizione. Sanremo ha più premi di quanto si pensi.",
  },
  {
    time: "01:56",
    type: "presentazione",
    label: "Premio TIM",
    description: "Consegnato all'artista più amato su app My Tim e social ufficiali TIM.",
    presenter: "Carlo Conti",
    guest: "Pietro Labiola",
    duration: "3'",
    aiContext: "Pietro Labiola, AD di TIM, consegna il premio all'artista più votato sull'app e sui social del brand. È un premio di popolarità digitale. Chi lo vince è probabilmente quello che ha i fan più organizzati su Instagram.",
  },
  {
    time: "01:59",
    type: "presentazione",
    label: "Ingresso 5 finalisti — rivelazione 5°, 4°, 3° posto",
    description: "Vengono eliminati il 5°, 4° e 3° classificato. Il sindaco Alessandro Mager porta il Leone d'Oro.",
    presenter: "Carlo Conti, Laura Pausini, Giorgia Cardinaletti, Nino Frassica",
    duration: "5'",
    aiContext: "I 5 finalisti salgono sul palco. Vengono eliminati tre. Il sindaco di Sanremo Alessandro Mager porta fisicamente il Leone d'Oro. Sono le 02:00. Chi è ancora sveglio ha guadagnato il diritto di assistere alla fine.",
  },
  {
    time: "02:04",
    type: "presentazione",
    label: "GM",
    duration: "1'",
    aiContext: "Ultimo spazio promozionale prima della proclamazione. Probabilmente nessuno lo guarda.",
  },
  {
    time: "02:05",
    type: "fine",
    label: "Proclamazione del vincitore",
    description: "Conti apre la busta e proclama il vincitore. Consegna del Leone d'Oro. Il vincitore esegue nuovamente il brano con l'orchestra. Ringraziamenti e saluti finali.",
    presenter: "Carlo Conti, Laura Pausini, Giorgia Cardinaletti, Nino Frassica",
    duration: "5'",
    aiContext: "Sono le 02:05. Conti apre la busta. Uno dei 30 artisti vince il 76° Festival di Sanremo e il diritto di rappresentare l'Italia all'Eurovision di Vienna. Il vincitore canta di nuovo. Tutti piangono. Fine.",
  },
];